// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSConstantIds
{
        public const string achievement_get_10_points = "CgkI4aminN4PEAIQAw"; // <GPGSID>
        public const string achievement_share_to_a_friend = "CgkI4aminN4PEAIQBg"; // <GPGSID>
        public const string achievement_first_try = "CgkI4aminN4PEAIQAg"; // <GPGSID>
        public const string achievement_get_20_points = "CgkI4aminN4PEAIQBQ"; // <GPGSID>
        public const string achievement_get_15_points = "CgkI4aminN4PEAIQBA"; // <GPGSID>
        public const string achievement_get_30_points = "CgkI4aminN4PEAIQBw"; // <GPGSID>
        public const string leaderboard_ranking = "CgkI4aminN4PEAIQAQ"; // <GPGSID>

}

